#This make file builds our golang Docker image
# and installs any neccessary items to run our web app

#Use this to run tests in 'testing-project'
run-test-proj:
	pwd
	go test ./golang/testing-project -v

#Use this to run our main go project
run-go-proj:
	go run ./golang/project/*.go